---
- hosts: all
  gather_facts: yes
  roles:
#    - role: rhel7STIG
#      when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7"
#    - role: rhel8STIG
#      when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8"
#    - role: rhel9STIG
#      when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "9"
    - role: DoD_Root_CAs
    - role: logrotate