---
- name: Install logrotate
  package:
    name: logrotate
    state: present

- name: Deploy logrotate configuration
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/common_logs
    owner: root
    group: root
    mode: '0644'
